[build]
  ignore = "/bin/false"
  base = ".massivewikibuilder"
  publish = "output"
  command = "./mwb.py -c mwb.yaml -w .. -o output -t massive-wiki-themes/alto"

[build.environment]
  PYTHON_VERSION = "3.8"
